# -*- coding: utf-8 -*-
"""Node_classification_using_social_network.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gBn-XfVCuWFGiTsAsmw-Dk0MM8tefSDv
"""

!pip install torch torchvision torchaudio --q
!pip install torch-geometric --q

import networkx as nx
import numpy as np

G = nx.Graph()
num_nodes = 60
num_classes = 3

labels = np.random.randint(0, num_classes, num_nodes)

for i in range(num_nodes):
    label = labels[i]

    feature = np.random.rand(3) + label * 0.3

    G.add_node(i, feature=feature, label=label)

for i in range(num_nodes):
    for j in range(i + 1, num_nodes):
        if labels[i] == labels[j]:
            prob = 0.3
        else:
            prob = 0.1

        if np.random.rand() < prob:
            G.add_edge(i, j)

import torch
from torch_geometric.data import Data

x = torch.tensor([G.nodes[i]['feature'] for i in G.nodes()], dtype=torch.float)
y = torch.tensor([G.nodes[i]['label'] for i in G.nodes()], dtype=torch.long)

edge_index = torch.tensor(list(G.edges())).t().contiguous()
edge_index = torch.cat([edge_index, edge_index.flip(0)], dim=1)

data = Data(x=x, edge_index=edge_index, y=y)

num_nodes = data.num_nodes

indices = torch.randperm(num_nodes)

train_size = int(0.8 * num_nodes)

train_mask = torch.zeros(num_nodes, dtype=torch.bool)
test_mask = torch.zeros(num_nodes, dtype=torch.bool)

train_mask[indices[:train_size]] = True
test_mask[indices[train_size:]] = True

data.train_mask = train_mask
data.test_mask = test_mask

import torch.nn.functional as F
from torch_geometric.nn import GCNConv

class GCN(torch.nn.Module):
    def __init__(self):
        super(GCN, self).__init__()
        self.conv1 = GCNConv(3, 16)
        self.conv2 = GCNConv(16, 3)

    def forward(self, x, edge_index):
        x = self.conv1(x, edge_index)
        x = F.relu(x)
        x = F.dropout(x, p=0.5, training=self.training)
        x = self.conv2(x, edge_index)
        return F.log_softmax(x, dim=1)

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

model = GCN().to(device)
data = data.to(device)

optimizer = torch.optim.Adam(model.parameters(), lr=0.01, weight_decay=5e-4)

def train():
    model.train()
    optimizer.zero_grad()

    out = model(data.x, data.edge_index)
    loss = F.nll_loss(out[data.train_mask], data.y[data.train_mask])

    loss.backward()
    optimizer.step()

    return loss.item()

def test():
    model.eval()
    out = model(data.x, data.edge_index)
    pred = out.argmax(dim=1)

    correct = pred[data.test_mask] == data.y[data.test_mask]
    acc = int(correct.sum()) / int(data.test_mask.sum())

    return acc

train_losses = []
test_acc_list = []

for epoch in range(1, 101):
    loss = train()
    acc = test()

    train_losses.append(loss)
    test_acc_list.append(acc)

    if epoch % 10 == 0:
        print(f"Epoch {epoch}, Loss: {loss:.4f}, Test Acc: {acc:.4f}")

import matplotlib.pyplot as plt

# Loss graph
plt.figure()
plt.plot(train_losses)
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.title("Training Loss")
plt.show()

# Accuracy graph
plt.figure()
plt.plot(test_acc_list, label="Test Accuracy")
plt.xlabel("Epoch")
plt.ylabel("Accuracy")
plt.title("Test Accuracy vs Epoch")
plt.legend()
plt.show()

from sklearn.metrics import classification_report, confusion_matrix

model.eval()
out = model(data.x, data.edge_index)
pred = out.argmax(dim=1)

y_true = data.y[data.test_mask].cpu()
y_pred = pred[data.test_mask].cpu()

print("Classification Report:\n")
print(classification_report(y_true, y_pred))

print("Confusion Matrix:\n")
print(confusion_matrix(y_true, y_pred))