# -*- coding: utf-8 -*-
"""Basic NLP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RUP1lRKjIIIZ9FAA7MLJazCaH3dMt9pZ
"""

import nltk

nltk.download('punkt_tab')

text = "Natural Language Processing is an exciting field of study."

text = text.lower()
print(text)

# tokenization
print(nltk.word_tokenize(text))

nltk.download('stopwords')

# stopword removal

print([word for word in nltk.word_tokenize(text) if word.lower() not in nltk.corpus.stopwords.words('english')])

# stopwords in english

print(nltk.corpus.stopwords.words('english'))

# stopwords in english

print(nltk.corpus.stopwords.words('french'))

nltk.download('wordnet')

# Stemming

print([nltk.stem.PorterStemmer().stem(word) for word in nltk.word_tokenize(text) if word not in set(nltk.corpus.stopwords.words('english'))])

# Lemmatization

print([nltk.stem.WordNetLemmatizer().lemmatize(word) for word in nltk.word_tokenize(text) if word not in set(nltk.corpus.stopwords.words('english'))])

!pip install contractions --quiet

import contractions

new_text = "I'll eat now"

# Contractions

print(contractions.fix(new_text))

!pip install emoji --quiet

import emoji

text2 = "Nice to meet you 😁"

# emoji removal

print(emoji.demojize(text2))

!pip uninstall spellchecker -y
!pip install pyspellchecker --quiet

from spellchecker import SpellChecker

text3 = "helllo worldd"

print([SpellChecker().correction(word) for word in nltk.word_tokenize(text3) if word not in set(nltk.corpus.stopwords.words('english'))])