# -*- coding: utf-8 -*-
"""Untitled21.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1axELSRlL--5JldO25Su0TKOvE3WzeIJ2
"""

import nltk

from nltk import pos_tag

nltk.download('averaged_perceptron_tagger')

nltk.download('punkt_tab')

from nltk.tokenize import word_tokenize
import nltk

nltk.download('averaged_perceptron_tagger_eng')
nltk.download('punkt_tab')

print(pos_tag(word_tokenize("Hello World")))