# -*- coding: utf-8 -*-
"""POS Tagging and NER.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NjWHvMOMpqMCZyhi-mY0wIEcFeszQmuP
"""

!pip install spacy stanza --quiet
!python -m spacy download en_core_web_sm --quiet

import spacy
import stanza
import re

nlp_en = spacy.load("en_core_web_sm")
stanza.download("hi")
nlp_hi = stanza.Pipeline("hi")

text = "NLP is amazing!!! यह बहुत अच्छा है 2025 @AI"

english_text = re.findall(r"[A-Za-z@]+|\d+", text)
hindi_text = re.findall(r"[\u0900-\u097F]+", text)

print("---- POS TAGGING ----")

doc_en = nlp_en(" ".join(english_text))
for token in doc_en:
    print(token.text, "->", token.pos_)

doc_hi = nlp_hi(" ".join(hindi_text))
for sent in doc_hi.sentences:
    for word in sent.words:
        print(word.text, "->", word.upos)

print("\n---- NER ----")

for ent in doc_en.ents:
    print(ent.text, "->", ent.label_)

for sent in doc_hi.sentences:
    for ent in sent.ents:
        print(ent.text, "->", ent.type)