# -*- coding: utf-8 -*-
"""TF_IDF_NLP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CXLNvwiAdjh9V57p1jZzm5kSlJMMDiTp
"""

Corpus = ["The cat sat on the mat.", "The dog played in the park.", "Cats and dogs are great pets."]

from sklearn.feature_extraction.text import TfidfVectorizer

print(TfidfVectorizer().fit_transform(Corpus))

vec = TfidfVectorizer()
r = vec.fit_transform(Corpus)

# TF-IDF Scores

for i, n in enumerate(r.toarray()):
  for word, score in zip(vec.get_feature_names_out(), n):
    print(word, ':', score)

# IDF Scores

for e1, e2 in zip(vec.get_feature_names_out(), vec.idf_):
    print(e1, ':', e2)