# -*- coding: utf-8 -*-
"""Data_Pre_Processing_Iris.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r81STJPkSwggMOydDZ9pcrphXKtofzZo
"""

import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from sklearn.feature_selection import SelectKBest, f_classif

# ===================== 1. Load Dataset =====================
df = pd.read_csv("iris.csv")   # change filename if needed

print("===== ORIGINAL DATASET =====")
print(df.head(), "\n")

# ===================== 2. Missing Value Handling =====================
for col in df.columns:
    if df[col].dtype == "object":
        df[col].fillna(df[col].mode()[0], inplace=True)
    else:
        df[col].fillna(df[col].mean(), inplace=True)

# ===================== 3. Normalization =====================
numeric_cols = df.select_dtypes(include=np.number).columns
scaler = MinMaxScaler()
df[numeric_cols] = scaler.fit_transform(df[numeric_cols])

# ===================== 4. Discretization =====================
col_to_bin = numeric_cols[0]   # first numeric column
df[col_to_bin + "_bin"] = pd.cut(df[col_to_bin], bins=3, labels=["Low", "Medium", "High"])

# ===================== 5. Attribute Selection =====================
X = df.drop(columns=[df.columns[-1]])  # features
y = df[df.columns[-1]]  # target

selector = SelectKBest(score_func=f_classif, k=2)
selector.fit(X.select_dtypes(include=np.number), y)

selected_features = X.select_dtypes(include=np.number).columns[selector.get_support()]

# Keep only selected attributes + target + discretized column
df_selected = df[selected_features.tolist() + [df.columns[-1], col_to_bin + "_bin"]]

# ===================== 6. Attribute Removal =====================
# Example: remove one attribute manually
if len(selected_features) > 1:
    df_selected = df_selected.drop(columns=[selected_features[0]])

# ===================== ✅ FINAL PREPROCESSED DATASET =====================
print("===== FINAL PREPROCESSED DATASET =====")
print(df_selected.head(20))   # print first 20 rows
print("\nShape of Final Dataset:", df_selected.shape)