# -*- coding: utf-8 -*-
"""RNN Model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n0jwpuHpWVFNwarzTL7PP80msMMtV-TJ
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import (classification_report, confusion_matrix,
                            mean_absolute_error, mean_squared_error, r2_score)
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, BatchNormalization
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau
from google.colab import files
import io
from math import sqrt
import warnings
warnings.filterwarnings('ignore')

SEED = 42
np.random.seed(SEED)
tf.random.set_seed(SEED)

#upload file -
print("Please upload your energy data CSV file:")
uploaded = files.upload()
file_name = list(uploaded.keys())[0]
df = pd.read_csv(io.BytesIO(uploaded[file_name]), encoding='utf-8-sig')
print(f"\nSuccessfully loaded '{file_name}'.")

def advanced_feature_engineering(df):
    feature_columns = [
        'Access to electricity (% of population)',
        'CO2 emissions (metric tons per capita)',
        'Energy use (kg of oil equivalent per capita)',
    ]

    # Clean and filter data
    df_clean = df.dropna(subset=['CO2 emissions (metric tons per capita)'])

    # Use per capita CO2 as target (much smaller scale)
    target_col = 'CO2 emissions (metric tons per capita)'

    # Advanced outlier removal using IQR
    def remove_outliers_iqr(data, column, factor=1.5):
        if column in data.columns:
            Q1 = data[column].quantile(0.25)
            Q3 = data[column].quantile(0.75)
            IQR = Q3 - Q1
            lower = Q1 - factor * IQR
            upper = Q3 + factor * IQR
            return data[(data[column] >= lower) & (data[column] <= upper)]
        return data

    df_clean = remove_outliers_iqr(df_clean, target_col)

    if len(df_clean) > 0:
        # Rolling statistics for CO₂ per capita
        df_clean = df_clean.sort_values('Years') if 'Years' in df_clean.columns else df_clean
        df_clean['CO2_ma_3'] = df_clean[target_col].rolling(3, min_periods=1).mean()
        df_clean['CO2_ma_5'] = df_clean[target_col].rolling(5, min_periods=1).mean()

        # Rate of change
        df_clean['CO2_pct_change'] = df_clean[target_col].pct_change().fillna(0)

        # Lag features
        for lag in [1, 2]:
            df_clean[f'CO2_lag_{lag}'] = df_clean[target_col].shift(lag)

        # Fill NaN values
        df_clean = df_clean.interpolate(method='linear').fillna(method='bfill').fillna(method='ffill')

    return df_clean

print("\nAdvanced feature engineering...")
df_processed = advanced_feature_engineering(df)

# Use per capita CO2 as target (key difference!)
target_col = 'CO2 emissions (metric tons per capita)'
if target_col not in df_processed.columns:
    raise ValueError(f"Target column '{target_col}' not found in the dataset.")

print(f"Target range: {df_processed[target_col].min():.2f} to {df_processed[target_col].max():.2f} metric tons per capita")

numeric_cols = df_processed.select_dtypes(include=np.number).columns
features = df_processed[numeric_cols].drop(target_col, axis=1)
X = features

y_reg = df_processed[target_col].values

y_class = pd.cut(df_processed[target_col],
                bins=[-np.inf, df_processed[target_col].quantile(0.33),
                      df_processed[target_col].quantile(0.66), np.inf],
                labels=[0, 1, 2]).astype('int32')

print(f"\nFeatures being used ({len(features.columns)} total):")
print(features.columns.tolist())

# Clean data function (from reference code)
def clean_data_for_scaling(data):
    """Clean data by replacing inf/-inf values and extreme outliers"""
    data_cleaned = data.copy()

    # Replace infinity values with NaN
    data_cleaned = np.where(np.isinf(data_cleaned), np.nan, data_cleaned)

    # Replace extremely large values
    data_cleaned = np.where(np.abs(data_cleaned) > 1e10, np.nan, data_cleaned)

    # Fill NaN values with median
    if data_cleaned.ndim == 2:
        for i in range(data_cleaned.shape[1]):
            feature_data = data_cleaned[:, i]
            median_val = np.nanmedian(feature_data)
            if np.isnan(median_val):
                median_val = 0
            data_cleaned[:, i] = np.where(np.isnan(data_cleaned[:, i]), median_val, data_cleaned[:, i])
    else:
        median_val = np.nanmedian(data_cleaned)
        if np.isnan(median_val):
            median_val = 0
        data_cleaned = np.where(np.isnan(data_cleaned), median_val, data_cleaned)

    return data_cleaned

# Train-test splits
X_train_class, X_test_class, y_train_class, y_test_class = train_test_split(
    X, y_class, test_size=0.1, random_state=42, stratify=y_class
)

X_train_reg, X_test_reg, y_train_reg, y_test_reg = train_test_split(
    X, y_reg, test_size=0.1, random_state=42
)

# Clean data before scaling (following reference approach)
X_train_reg_clean = clean_data_for_scaling(X_train_reg.values)
y_train_reg_clean = clean_data_for_scaling(y_train_reg)
X_test_reg_clean = clean_data_for_scaling(X_test_reg.values)
y_test_reg_clean = clean_data_for_scaling(y_test_reg)

X_train_class_clean = clean_data_for_scaling(X_train_class.values)
X_test_class_clean = clean_data_for_scaling(X_test_class.values)

# Use MinMaxScaler like the reference code
scaler_X = MinMaxScaler()
scaler_y = MinMaxScaler()

# Scale features
X_train_class_scaled = scaler_X.fit_transform(X_train_class_clean)
X_test_class_scaled = scaler_X.transform(X_test_class_clean)

X_train_reg_scaled = scaler_X.fit_transform(X_train_reg_clean)
X_test_reg_scaled = scaler_X.transform(X_test_reg_clean)

# Scale target variable
y_train_reg_scaled = scaler_y.fit_transform(y_train_reg_clean.reshape(-1, 1)).flatten()
y_test_reg_scaled = scaler_y.transform(y_test_reg_clean.reshape(-1, 1)).flatten()

def build_classification_model(input_shape):
    model = Sequential([
        Dense(64, activation='relu', input_shape=(input_shape,)),
        BatchNormalization(),
        Dropout(0.2),

        Dense(32, activation='relu'),
        BatchNormalization(),
        Dropout(0.2),

        Dense(16, activation='relu'),
        BatchNormalization(),
        Dropout(0.1),

        Dense(3, activation='softmax')
    ])

    model.compile(optimizer=Adam(learning_rate=0.001),
                  loss='sparse_categorical_crossentropy',
                  metrics=['accuracy'])
    return model

print("\nBuilding classification model...")
class_model = build_classification_model(X_train_class_scaled.shape[1])
class_model.summary()

early_stopping_class = EarlyStopping(monitor='val_accuracy', patience=10,
                                    restore_best_weights=True, verbose=1)
reduce_lr_class = ReduceLROnPlateau(monitor='val_loss', factor=0.8,
                                   patience=3, min_lr=0.00001)

print("\nTraining the classification model...")
history_class = class_model.fit(
    X_train_class_scaled, y_train_class,
    validation_split=0.2,
    epochs=100,
    batch_size=32,
    callbacks=[early_stopping_class, reduce_lr_class],
    verbose=1
)

print("\nEvaluating classification model performance...")
test_loss_class, test_acc_class = class_model.evaluate(X_test_class_scaled, y_test_class, verbose=0)
print(f"\nClassification Test Accuracy: {test_acc_class*100:.2f}%")

y_pred_probs = class_model.predict(X_test_class_scaled)
y_pred_class = np.argmax(y_pred_probs, axis=1)

mae_class = mean_absolute_error(y_test_class, y_pred_class)
rmse_class = sqrt(mean_squared_error(y_test_class, y_pred_class))
print(f"\n Classification Mean Absolute Error (MAE): {mae_class:.1f}")
print(f" Classification Root Mean Squared Error (RMSE): {rmse_class:.4f}")

plt.figure(figsize=(18, 6))

plt.subplot(1, 2, 1)
plt.plot(history_class.history['accuracy'], label='Train Accuracy', color='#4e79a7')
plt.plot(history_class.history['val_accuracy'], label='Validation Accuracy', color='#f28e2b')
plt.title('Classification Model Accuracy', fontsize=16)
plt.xlabel('Epoch', fontsize=12)
plt.ylabel('Accuracy', fontsize=12)
plt.legend(loc='lower right')

plt.subplot(1, 2, 2)
plt.plot(history_class.history['loss'], label='Train Loss', color='#4e79a7')
plt.plot(history_class.history['val_loss'], label='Validation Loss', color='#f28e2b')
plt.title('Classification Model Loss', fontsize=16)
plt.xlabel('Epoch', fontsize=12)
plt.ylabel('Loss', fontsize=12)
plt.legend(loc='upper right')
plt.show()

# Classification report and confusion matrix
print("\nClassification Report:")
print(classification_report(y_test_class, y_pred_class,
                          target_names=['Low', 'Medium', 'High']))

cm = confusion_matrix(y_test_class, y_pred_class)
plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=['Low', 'Medium', 'High'],
            yticklabels=['Low', 'Medium', 'High'])
plt.title('Classification Confusion Matrix', fontsize=16)
plt.xlabel('Predicted Label', fontsize=12)
plt.ylabel('True Label', fontsize=12)
plt.show()

def build_regression_model(input_shape):
    model = Sequential([
        Dense(64, activation='relu', input_shape=(input_shape,)),
        BatchNormalization(),
        Dropout(0.3),

        Dense(32, activation='relu'),
        BatchNormalization(),
        Dropout(0.2),

        Dense(16, activation='relu'),
        BatchNormalization(),
        Dropout(0.1),

        Dense(1)  # Linear output for regression
    ])

    model.compile(optimizer=Adam(learning_rate=0.001),
                  loss='mse',
                  metrics=['mae'])
    return model

print("\nBuilding regression model...")
reg_model = build_regression_model(X_train_reg_scaled.shape[1])
reg_model.summary()

early_stopping_reg = EarlyStopping(monitor='val_loss', patience=15,
                                 restore_best_weights=True)
reduce_lr_reg = ReduceLROnPlateau(monitor='val_loss', factor=0.8,
                                patience=5, min_lr=0.00001)

print("\nTraining the regression model...")
history_reg = reg_model.fit(
    X_train_reg_scaled, y_train_reg_scaled,  # Train on scaled per capita data
    validation_split=0.2,
    epochs=150,
    batch_size=32,
    callbacks=[early_stopping_reg, reduce_lr_reg],
    verbose=1
)

print("\nEvaluating regression model performance...")
test_loss_reg, test_mae_reg = reg_model.evaluate(X_test_reg_scaled, y_test_reg_scaled, verbose=0)
y_pred_reg_scaled = reg_model.predict(X_test_reg_scaled).flatten()

# Transform predictions back to original scale
y_pred_reg_original = scaler_y.inverse_transform(y_pred_reg_scaled.reshape(-1, 1)).flatten()

# Calculate metrics on original scale (per capita)
mae_reg = mean_absolute_error(y_test_reg_clean, y_pred_reg_original)
mse_reg = mean_squared_error(y_test_reg_clean, y_pred_reg_original)
rmse_reg = sqrt(mse_reg)
r2 = r2_score(y_test_reg_clean, y_pred_reg_original)

print(f"\nRegression Mean Absolute Error (MAE): {mae_reg:.1f} metric tons per capita")
print(f"Regression Mean Squared Error (MSE): {mse_reg:.4f} metric tons per capita")
print(f"Regression Root Mean Squared Error (RMSE): {rmse_reg:.4f} metric tons per capita")
print(f"R-squared (R²): {r2:.4f}")

plt.figure(figsize=(18, 6))

# Actual vs Predicted with regression line
plt.subplot(1, 2, 1)
sns.regplot(x=y_test_reg_clean, y=y_pred_reg_original,
            scatter_kws={'alpha':0.6, 'color':'#4e79a7'},
            line_kws={'color':'#e15759', 'lw':2})
plt.title(f'Actual vs Predicted Values\n$R^2$ = {r2:.4f}', fontsize=16)
plt.xlabel('Actual Values (metric tons per capita)', fontsize=12)
plt.ylabel('Predicted Values (metric tons per capita)', fontsize=12)
plt.grid(True, linestyle='--', alpha=0.5)

# Residuals plot
plt.subplot(1, 2, 2)
residuals = y_test_reg_clean - y_pred_reg_original
sns.scatterplot(x=y_pred_reg_original, y=residuals, alpha=0.6, color='#4e79a7')
plt.axhline(y=0, color='#e15759', linestyle='--')
plt.title(f'Residuals Plot\nMean: {np.mean(residuals):.3f}  Std: {np.std(residuals):.3f}', fontsize=16)
plt.xlabel('Predicted Values (metric tons per capita)', fontsize=12)
plt.ylabel('Residuals', fontsize=12)
plt.grid(True, linestyle='--', alpha=0.5)

plt.tight_layout()
plt.show()

# Training history for regression
plt.figure(figsize=(18, 6))

plt.subplot(1, 2, 1)
plt.plot(history_reg.history['mae'], label='Train MAE', color='#4e79a7')
plt.plot(history_reg.history['val_mae'], label='Validation MAE', color='#f28e2b')
plt.title('Regression Model MAE Over Epochs', fontsize=16)
plt.xlabel('Epoch', fontsize=12)
plt.ylabel('MAE', fontsize=12)
plt.legend()

plt.subplot(1, 2, 2)
plt.plot(history_reg.history['loss'], label='Train Loss', color='#4e79a7')
plt.plot(history_reg.history['val_loss'], label='Validation Loss', color='#f28e2b')
plt.title('Regression Model Loss Over Epochs', fontsize=16)
plt.xlabel('Epoch', fontsize=12)
plt.ylabel('MSE', fontsize=12)
plt.legend()

plt.tight_layout()
plt.show()

print("\n Combined Model Insights ")
print(f"Classification Approach:")
print(f"- Accuracy: {test_acc_class*100:.2f}%")
print(f"- MAE between classes: {mae_class:.1f}")

print(f"\nRegression Approach (Per Capita CO2):")
print(f"- MAE: {mae_reg:.1f} metric tons per capita")
print(f"- MSE: {mse_reg:.4f} metric tons per capita")
print(f"- RMSE: {rmse_reg:.4f} metric tons per capita")
print(f"- R²: {r2:.4f}")

# Show distribution of actual per capita CO2 emissions
plt.figure(figsize=(12, 6))
sns.histplot(df_processed[target_col], bins=30, kde=True, color='#4e79a7')
plt.title('Distribution of CO2 Emissions (Per Capita)', fontsize=16)
plt.xlabel('CO2 Emissions (metric tons per capita)', fontsize=12)
plt.ylabel('Frequency', fontsize=12)
plt.show()

# print(f"\nData Summary:")
# print(f"Per capita CO2 range: {df_processed[target_col].min():.2f} to {df_processed[target_col].max():.2f} metric tons")
# print(f"Per capita CO2 mean: {df_processed[target_col].mean():.2f} metric tons")
# print(f"Per capita CO2 std: {df_processed[target_col].std():.2f} metric tons")

if 'Years' not in df.columns:
    # Try to infer a year column (customize if needed)
    raise ValueError("A numeric 'Years' column is required for year-based prediction.")

df['Years'] = pd.to_numeric(df['Years'], errors='coerce')
df = df.dropna(subset=['Years'])

def advanced_feature_engineering(df):
    target_col = 'CO2 emissions (metric tons per capita)'
    if target_col not in df.columns:
        raise ValueError(f"Target column '{target_col}' not found.")

    # Keep only rows with target
    df_clean = df.dropna(subset=[target_col]).copy()

    # IQR outlier removal on target
    def remove_outliers_iqr(data, column, factor=1.5):
        if column in data.columns:
            Q1 = data[column].quantile(0.25)
            Q3 = data[column].quantile(0.75)
            IQR = Q3 - Q1
            lower = Q1 - factor * IQR
            upper = Q3 + factor * IQR
            return data[(data[column] >= lower) & (data[column] <= upper)]
        return data

    df_clean = remove_outliers_iqr(df_clean, target_col)

    # Sort strictly by Years for time features
    df_clean = df_clean.sort_values('Years')

    # Rolling features on target
    df_clean['CO2_ma_3'] = df_clean[target_col].rolling(3, min_periods=1).mean()
    df_clean['CO2_ma_5'] = df_clean[target_col].rolling(5, min_periods=1).mean()

    # Rate of change
    df_clean['CO2_pct_change'] = df_clean[target_col].pct_change().fillna(0)

    # Lags
    for lag in [1, 2]:
        df_clean[f'CO2_lag_{lag}'] = df_clean[target_col].shift(lag)

    # Interpolate forward in time then backfill edges
    df_clean = df_clean.interpolate(method='linear').fillna(method='bfill').fillna(method='ffill')

    return df_clean

df_processed = advanced_feature_engineering(df)

target_col = 'CO2 emissions (metric tons per capita)'
numeric_cols = df_processed.select_dtypes(include=np.number).columns.tolist()
if target_col not in df_processed.columns:
    raise ValueError(f"Target column '{target_col}' not found after processing.")
feature_cols = [c for c in numeric_cols if c != target_col]  # 'Years' stays in
X = df_processed[feature_cols].copy()
y_reg = df_processed[target_col].values

def predict_for_year(target_year, df_full, df_proc, model, scaler_X, scaler_y, feature_cols, target_col):
    """
    Build a one-row feature vector for 'target_year' using the most recent known history,
    recompute rolling and lag features up to that year, then predict CO2 per capita.
    """
    if 'Years' not in df_proc.columns:
        raise ValueError("'Years' column is missing in processed data.")
    base = df_full.copy()
    base = base.sort_values('Years')

    for col in ['CO2_ma_3','CO2_ma_5','CO2_pct_change','CO2_lag_1','CO2_lag_2']:
        if col not in df_proc.columns:
            pass

    needed_cols = set(['Years', target_col]) | set([c for c in feature_cols if c in base.columns])
    base = base[[c for c in needed_cols if c in base.columns]].copy()

    last_known_year = int(base['Years'].max())
    if target_year <= last_known_year:
        df_ext = df_proc.copy()
    else:
        missing_years = [y for y in range(last_known_year + 1, target_year + 1)]
        new_rows = pd.DataFrame({'Years': missing_years})
        df_ext = pd.concat([base, new_rows], ignore_index=True)
        df_ext = df_ext.sort_values('Years')

        df_ext = advanced_feature_engineering(df_ext)

    if target_year not in df_ext['Years'].values:
        raise ValueError(f"Target year {target_year} not present after extension.")

    row = df_ext[df_ext['Years'] == target_year].copy()

    missing_feats = [c for c in feature_cols if c not in row.columns]
    if missing_feats:
        for c in missing_feats:
            row[c] = 0.0

    x_row = row[feature_cols].values.astype(float)

    x_row_clean = clean_data_for_scaling(x_row)
    x_row_scaled = scaler_X.transform(x_row_clean)

    y_pred_scaled = model.predict(x_row_scaled, verbose=0).flatten()
    y_pred = scaler_y.inverse_transform(y_pred_scaled.reshape(-1, 1)).flatten()[0]

    return float(y_pred)

try:
    year_input = int(input("Enter a year to predict CO2 emissions (per capita): ").strip())
    pred_value = predict_for_year(
        target_year=year_input,
        df_full=df,              # original full DF
        df_proc=df_processed,    # processed/engineered DF
        model=reg_model,         # trained regression model
        scaler_X=scaler_X,       # feature scaler fitted on training
        scaler_y=scaler_y,       # target scaler fitted on training
        feature_cols=feature_cols,
        target_col=target_col
    )
    print(f"Predicted CO2 emissions in {year_input}: {pred_value:.3f} metric tons per capita")
except Exception as e:
    print(f"Prediction failed: {e}")