# -*- coding: utf-8 -*-
"""Basic Statistical Operations.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13BkoR7ez4tF_vDZ-egtdvlHqRJhvblL0
"""

import numpy as np

a=np.array([1,2,3,4,5])

# standard python method to get mean

a.mean()

# numpy method to get mean

np.mean(a)

# standard python method to get variance

a.var()

# standard python method to get standard deviation

a.std()

# numpy method to get variance

np.var(a)

# numpy method to get standard deviation

np.std(a)

# numpy method to get median. There is no standard python method for this. But we can use the Statistics module.

np.median(a)

# similarly we can perform these for 2D array or higher dimensional arrays.

a=np.array([[1,2,3],[4,5,6]])

a.mean(), a.std(), a.var, np.median(a)