# -*- coding: utf-8 -*-
"""Concatenation_and_Sorting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13BkoR7ez4tF_vDZ-egtdvlHqRJhvblL0
"""

import numpy as np

a =  np.array([[1,2,3,4,5],[6,7,8,9,10]])

a.ndim

b = np.array([1, 2, 3, 4, 5])
c = np.array([10, 9, 8, 7, 6])
b, c

# The concatenate function is used to concatenate 2 arrays.

d = np.concatenate([b, c])
d

# This is how we sort the array.

d.sort()
d

# This will throw an error because we cannot concatenate 2 arrays which are different in dimensions.

e = np.concatenate([a,b])

# So we need to convert b to a 2D array.

b = np.array([1, 2, 3, 4, 5])
b
f = np.array(b).reshape(-1,1)
f.ndim

"""
If anywhere we specify the value as -1 then it finds out the best dimension of the array.
Instead of -1 we could have wrote 1 but the result will be same as the it is only dimension the array can exist after concatenation.
"""

a = np.array(a).reshape(-1,2)
a
e = np.concatenate([f,a], axis=-1)
e

"""
This is how vertically stack arrays using vstack function.
For this we need equal number of columns.
"""
a=a.reshape(-1,1)
np.vstack([f,a])

"""
This is how we do horizontal stacking.
We need to have equal number of rows here.
"""

a=a.reshape(5,2)
np.hstack([f,a])