# -*- coding: utf-8 -*-
"""NaN & inf.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13BkoR7ez4tF_vDZ-egtdvlHqRJhvblL0
"""

import numpy as np

"""
np.nan: in numpy nan stands for not a number which means a datatype which numpy cannot understand.
np.inf: in numpy inf stands for infinite which means it is beyond its capabilities to perform calculations on that.
"""

# We cannot compare 2 nan

np.nan==np.nan, np.nan>np.nan, np.nan<np.nan

# But we can compare inf

np.inf == np.inf, np.inf > np.inf, np.inf < np.inf

# There is None Data type also which we compare only == and not > or <

None==None

# This will throw an error

None>None

# This shows that nan is of float type so it is of 64 bits so we cannot directly convert any integer to nan, we need to convert it to float and then nan.

a = np.nan

type(a)

a = np.array([[1,2,3],[4,5,6]], dtype='f')
a.shape, a.dtype, a

# This will throw an error initially as we have not converted int to floatL

a[0][1] = np.nan
a[0][2] = np.inf

# Now it will not throw an error because now we have converted int to float and then we convert the floating point numbers to nan.

a[0][1] = np.nan
a[0][2] = np.inf

# This we replace all the numbers will boolean values and the place which had nan will be shown as 'True'.

np.isnan(a)

# This we replace all the numbers will boolean values and the place which had inf will be shown as 'True'.

np.isinf(a)

