# -*- coding: utf-8 -*-
"""Numpy-Array.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13BkoR7ez4tF_vDZ-egtdvlHqRJhvblL0
"""

import numpy as np

np.__version__

# This creates a numpy array. It can be a list, tuple, etc.
a = np.array([1,2,3])

a

# This will show that `a` is a type of numpy array.
type(a)

# ndarray means n dimensional array.

# This will print basically the size of the array.
a.shape

# This will give the dimension of the array.
a.ndim

b = np.array((1,2,3))

# This will give the same result as the results before which was for an array instead here we have used tuple here.
b, type(b), b.shape, b.ndim

# 0 dimensional array

c = np.array(1)

# Here the c.shape gives nothing because a single number is a scalar and not a vector therefore it has no dimension. Since it has no dimension the size of the that dimension cannot be obtained.
c, type(c), c.shape, c.ndim

# 2 dimensional array

d = np.array([[1,2,3],[4,5,6]])

"""
Here for d.shape we get 2 values which is (2,3).
The 2 shows the number of rows and 3 shows the number of columns.
"""
d, type(d), d.shape, d.ndim

# 3 dimensional array

e = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

"""
This shows that 3 dimensional array is a list of 2 dimensional array.
Similarly n dimensional array is a list of n-1 dimensional array.
Also, Here e.shape prints 2,2,3 which means there are 2 arrays in which there are 2 rows with 2 columns each.
Also, to get the number of dimensions just count the number of opening brackets or closing brackets.
In our case there are 3 opening and closing brackets therefore the number of dimensions is 3.
"""
e, type(e), e.shape, e.ndim

# We can do this as well instead of writing e.ndim as both gives the number of dimensions.

len(e.shape)