# -*- coding: utf-8 -*-
"""Numpy_Array_Read_and_Write.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13BkoR7ez4tF_vDZ-egtdvlHqRJhvblL0
"""

import numpy as np

a =  np.array([[1,2,3,4,5],[6,7,8,9,10]])

a.ndim

# This saves the array as a binary numpy format.

np.save('a.npy', a)

"""
This saves the array in a text file.
Delimiter determines how to separate the values in a array.
"""

np.savetxt('a.txt', a, delimiter=',')

b = np.array([a, a])
b.ndim

# This saves the file as a csv binary numpy format.

np.savetxt('a.csv', a)

# This will throw an error because csv can store 2D array values and not 3D array values.

np.savetxt('b.csv', b)

# So we have to store it in a binary numpy array format.

b = np.save('b.npy', b)

"""
Loading the data from files.

The 'loadtxt' function converts the data to a floating point datatype if it is in a int datatype.
"""

print(np.loadtxt('a.txt', delimiter=','))

# This will throw an error because it can load only binary numpy format unless the file is specified to load by other functions.

print(np.load('a.txt'))

# The 'load' function do not change the datatype to floating point type rather it keeps the data as it is.

print(np.load('a.npy'))

"""
This saves the file in npz format.
Also it is used to save multiple numpy arrays together without concatenating them.
"""

np.savez('together.npz', a, b)

"""
This shows the arrays which are stored in the file but not their content.
For fetching the content we need to use the indexes to get the data.
"""

print(np.load('together.npz'))

# This is how we get the value for the arrays in a file of npz type.

c = np.load('together.npz')
print(c.files)
c['arr_0']