# -*- coding: utf-8 -*-
"""Numpy Array Indexing and Slicing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13BkoR7ez4tF_vDZ-egtdvlHqRJhvblL0
"""

import numpy as np

a = np.array([1,2,3])

print(a[1])

a[1]

b = np.array([[1,2,3],[4,5,6]])

print(b[1][2])

# We can write it like this also.
print(b[1,2])

c = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

c[0][1][-1]

# We can write like this also.
c[0][1,-1]

# to select the entire row then we write colon `:`.

"""
This means we first select the 2nd vector `1`.
Then select all the vectors inside of it using `:`.
Then at last we only select the last element of those vectors which we selected at the previous step.
"""
c[1,:,-1]

"""
This means we first select the 2nd vector `1`.
Then select all the vectors inside of it using `:`.
At last we select all the elements from 0 index to (2-1) index which is 1.
For the last index we always select 1 minus from it.
"""
c[1,:, 0:2]