# -*- coding: utf-8 -*-
"""Where.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13BkoR7ez4tF_vDZ-egtdvlHqRJhvblL0
"""

import numpy as np

a=np.array([[1,2,3,4,5,6,7,8,9,10],[11,12,13,14,15,16,17,18,19,20]])
a

# This does not returns the value rather it returns the indexes where the values are greater than 10

np.where(a>10)

# it will throw an error as it expects only 1 argument and not 2.

np.where(a>10 and a<5)

"""
To do this type of operation then we need to do it in 2 steps:
1) First get the values for the 1st condition.
2) Second get the values for the 2nd condition.
"""


b = np.where(a<10)
c =  a[b]
print(c)
d = np.where(c>5)
print(c[d])

# This displays the index of the stacked array which contains the max value.

a.argmax()

# This will throw an error because as argmax returns the index in terms of stacked array.

a[a.argmax()]

# It is similar to argmax the only difference is it returns the index of the minimum number in terms of stacked array.

a.argmin()

# This will return the max value in the array.

a.flatten()[a.argmax()], a.max()

a.flatten()[a.argmin()], a.min()