# -*- coding: utf-8 -*-
"""Reinforcement_Learning_in_Tic_Tac_Toe.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dSK9lsi6Fm35na2b00PGMtnmj-bdEPoC
"""

import random

alpha = 0.8
gamma = 0.95
epsilon = 0.2
episodes = 50000

def empty_board():
    return [' '] * 9

def available_moves(b):
    return [i for i in range(9) if b[i] == ' ']

def check_winner(b):
    wins = [(0,1,2),(3,4,5),(6,7,8),(0,3,6),(1,4,7),(2,5,8),(0,4,8),(2,4,6)]
    for x,y,z in wins:
        if b[x] == b[y] == b[z] and b[x] != ' ':
            return b[x]
    return None

Q = {}

def get_q(state, action):
    return Q.get((tuple(state), action), 0)

def update_q(state, action, reward, next_state):
    best = max([get_q(next_state,a) for a in available_moves(next_state)], default=0)
    Q[(tuple(state), action)] = get_q(state,action) + alpha*(reward + gamma*best - get_q(state,action))

def choose_action(state):
    if random.random() < epsilon:
        return random.choice(available_moves(state))
    qs = [get_q(state,a) for a in available_moves(state)]
    return available_moves(state)[qs.index(max(qs))]

for _ in range(episodes):
    board = empty_board()
    memory = []

    while True:
        action = choose_action(board)
        prev = board.copy()
        board[action] = 'X'
        memory.append((prev, action))

        if check_winner(board) == 'X':
            for s,a in memory:
                update_q(s, a, 1, board)
            break

        if not available_moves(board):
            for s,a in memory:
                update_q(s, a, 0, board)
            break

        opp = random.choice(available_moves(board))
        board[opp] = 'O'

        if check_winner(board) == 'O':
            for s,a in memory:
                update_q(s, a, -1, board)
            break

def play():
    board = empty_board()
    while True:
        print(board[0:3], board[3:6], board[6:9])
        move = int(input("Your move: "))
        board[move] = 'O'

        if check_winner(board) == 'O':
            print("You win")
            break

        ai = choose_action(board)
        board[ai] = 'X'

        if check_winner(board) == 'X':
            print("AI wins")
            break

play()